EatMeAgain/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EatMeAgain.Models
{
    public class Recipe
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int PreepTime { get; set; }
        public string Instruction { get; set; }

        public ICollection<IngredientList> IngredientLists { get; set; }
    }
}

EatMeAgain/Controllers/IngredientListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EatMeAgain.Data;
using EatMeAgain.Models;

namespace EatMeAgain.Controllers
{
    public class IngredientListsController : Controller
    {
        private readonly RecipeContext _context;

        public IngredientListsController(RecipeContext context)
        {
            _context = context;
        }

        // GET: IngredientLists
        public async Task<IActionResult> Index()
        {
            var recipeContext = _context.IngredientLists.Include(i => i.Ingredient).Include(i => i.Measure).Include(i => i.Recipe);
            return View(await recipeContext.ToListAsync());
        }

        // GET: IngredientLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredientList = await _context.IngredientLists
                .Include(i => i.Ingredient)
                .Include(i => i.Measure)
                .Include(i => i.Recipe)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (ingredientList == null)
            {
                return NotFound();
            }

            return View(ingredientList);
        }

        // GET: IngredientLists/Create
        public IActionResult Create()
        {
            ViewData["Ingredient"] = new SelectList(_context.Ingredients, "ID", "Name");
            ViewData["Measure"] = new SelectList(_context.Measures, "ID", "Name");
            ViewData["Recipe"] = new SelectList(_context.Recipes, "ID", "Name");
            return View();
        }

        // POST: IngredientLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Quantity,RecipeID,Ingredient,Measure")] IngredientList ingredientList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ingredientList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IngredientID"] = new SelectList(_context.Ingredients, "ID", "ID", ingredientList.IngredientID);
            ViewData["MeasureID"] = new SelectList(_context.Measures, "ID", "ID", ingredientList.MeasureID);
            ViewData["RecipeID"] = new SelectList(_context.Recipes, "ID", "ID", ingredientList.RecipeID);
            return View(ingredientList);
        }

        // GET: IngredientLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredientList = await _context.IngredientLists.FindAsync(id);
            if (ingredientList == null)
            {
                return NotFound();
            }
            ViewData["Ingredient"] = new SelectList(_context.Ingredients, "Name", "Name", ingredientList.IngredientID);
            ViewData["Measure"] = new SelectList(_context.Measures, "Name", "Name", ingredientList.MeasureID);
            ViewData["Recipe"] = new SelectList(_context.Recipes, "Name", "Name", ingredientList.RecipeID);
            return View(ingredientList);
        }

        // POST: IngredientLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Quantity,RecipeID,IngredientID,MeasureID")] IngredientList ingredientList)
        {
            if (id != ingredientList.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ingredientList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IngredientListExists(ingredientList.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IngredientID"] = new SelectList(_context.Ingredients, "ID", "ID", ingredientList.IngredientID);
            ViewData["MeasureID"] = new SelectList(_context.Measures, "ID", "ID", ingredientList.MeasureID);
            ViewData["RecipeID"] = new SelectList(_context.Recipes, "ID", "ID", ingredientList.RecipeID);
            return View(ingredientList);
        }

        // GET: IngredientLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredientList = await _context.IngredientLists
                .Include(i => i.Ingredient)
                .Include(i => i.Measure)
                .Include(i => i.Recipe)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (ingredientList == null)
            {
                return NotFound();
            }

            return View(ingredientList);
        }

        // POST: IngredientLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ingredientList = await _context.IngredientLists.FindAsync(id);
            _context.IngredientLists.Remove(ingredientList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IngredientListExists(int id)
        {
            return _context.IngredientLists.Any(e => e.ID == id);
        }
    }
}

EatMeAgain/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EatMeAgain.Data;
using EatMeAgain.Models;

namespace EatMeAgain.Controllers
{
    public class RecipesController : Controller
    {
        private readonly RecipeContext _context;

        public RecipesController(RecipeContext context)
        {
            _context = context;
        }

        // GET: Recipes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Recipes.ToListAsync());
        }

        // GET: Recipes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes
                .Include(r => r.IngredientLists)
                    .ThenInclude(iL => iL.Ingredient)
                .Include(r => r.IngredientLists)
                    .ThenInclude(iL => iL.Measure)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);

            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // GET: Recipes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,PreepTime,Instruction")] Recipe recipe)
        {
            try
            {
                if (ModelState.IsValid)
            {
                _context.Add(recipe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return View(recipe);
        }

        // GET: Recipes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes.FindAsync(id);
            if (recipe == null)
            {
                return NotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var recipeToUpdate = await _context.Recipes.FirstOrDefaultAsync(r => r.ID == id);
            if (await TryUpdateModelAsync<Recipe>(
                recipeToUpdate,
                "",
                r => r.Name, r => r.PreepTime, r => r.Instruction))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }
            return View(recipeToUpdate);
        }

        // GET: Recipes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recipe = await _context.Recipes.FindAsync(id);
            _context.Recipes.Remove(recipe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeExists(int id)
        {
            return _context.Recipes.Any(e => e.ID == id);
        }
    }
}

EatMeAgain/Views/Recipes/Create.cshtml
@model EatMeAgain.Models.Recipe

@{
    ViewData["Title"] = "Create";
}

<h1>Dodaj przepis</h1>

<h4>Przepisy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nazwa przepisu</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreepTime" class="control-label">Czas przygotowania</label>
                <input asp-for="PreepTime" class="form-control" />
                <span asp-validation-for="PreepTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instruction" class="control-label">Instrukcja</label>
                <input asp-for="Instruction" class="form-control" />
                <span asp-validation-for="Instruction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Stwórz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wróć</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EatMeAgain/Views/Recipes/Delete.cshtml
@model EatMeAgain.Models.Recipe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreepTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreepTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Instruction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Instruction)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EatMeAgain/Views/Recipes/Details.cshtml
@model EatMeAgain.Models.Recipe

@{
    ViewData["Title"] = "Details";
}

<h1>Szczegóły przepisu</h1>

<div>
    <h4>Przepis</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nazwa przepisu
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Przygotowanie
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PreepTime) minut
        </dd>
        <dt class="col-sm-2">
            Instrukcja
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Instruction)
        </dd>

        <dt class="col-sm-2">
            Lista składników
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Składnik</th>
                    <th>Ilość</th>
                    <th>Miara</th>
                    <th></th>
                </tr>
                @foreach (var item in Model.IngredientLists)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ingredient.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Measure.Name)
                        </td>
                        <td>
                            <a asp-controller="IngredientLists" asp-action="Edit" asp-route-id="@item.ID">Edytuj</a> |
                            <a asp-controller="IngredientLists" asp-action="Details" asp-route-id="@item.ID">Szczegóły</a> |
                            <a asp-controller="IngredientLists" asp-action="Delete" asp-route-id="@item.ID">Usuń</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Recipes" asp-action="Edit" asp-route-id="@Model.ID">Edytuj</a> |
    <a asp-controller="Recipes" asp-action="Index">Wroć</a> |
    <a asp-controller="IngredientLists" asp-action="Create">Dodaj składnik</a>
</div>

EatMeAgain/Views/Recipes/Edit.cshtml
@model EatMeAgain.Models.Recipe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edytuj</h1>

<h4>Przepis</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nazwa przepisu</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreepTime" class="control-label">Czas przygotowania</label>
                <input asp-for="PreepTime" class="form-control" />
                <span asp-validation-for="PreepTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instruction" class="control-label">Instrukcja</label>
                <input asp-for="Instruction" class="form-control" />
                <span asp-validation-for="Instruction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wróć</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EatMeAgain/Views/Recipes/Index.cshtml
@model IEnumerable<EatMeAgain.Models.Recipe>

@{
    ViewData["Title"] = "Index";
}

<h1>Przepisy</h1>

<p>
    <a asp-action="Create">Stwórz przepis</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Przepis</th>
            <th>Przygotowanie</th>
            <th>Instrukcja</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name) 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreepTime) minut
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Instruction)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edytuj</a>
                <a asp-action="Details" asp-route-id="@item.ID">Szczegóły</a>
                <a asp-action="Delete" asp-route-id="@item.ID">Usuń</a>
            </td>
        </tr>
}
    </tbody>
</table>